use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

use crate::hook_merge;

fn wrapper_path(global: bool) -> Option<PathBuf> {
    if global {
        mux_core::platform::home_dir().map(|h| h.join(".local").join("bin").join("aider"))
    } else {
        Some(PathBuf::from(".bin").join("aider"))
    }
}

pub fn run(args: &[String]) -> i32 {
    let mut uninstall = false;
    let mut global = false;

    for arg in args.iter().skip(1) {
        if arg == "--uninstall" {
            uninstall = true;
        } else if arg == "--global" {
            global = true;
        }
    }

    match args.first().map(String::as_str) {
        Some("install-hooks") => run_install(uninstall, global),
        _ => {
            eprintln!("mtyx: usage: mtyx aider install-hooks [--uninstall] [--global]");
            2
        }
    }
}

fn run_install(uninstall: bool, global: bool) -> i32 {
    let Some(path) = wrapper_path(global) else {
        eprintln!("error: could not resolve home directory for global wrapper");
        return 1;
    };

    if uninstall {
        if path.exists() {
            if let Err(e) = fs::remove_file(&path) {
                eprintln!("error removing {}: {e}", path.display());
                return 1;
            }
            println!("Successfully removed aider wrapper from {}", path.display());
        } else {
            println!("No aider wrapper found at {}", path.display());
        }
        0
    } else {
        if let Some(parent) = path.parent() {
            let _ = fs::create_dir_all(parent);
        }

        // Resolve real aider at install time and embed its absolute path.
        // This avoids the runtime `which -a aider` dance (which silently
        // fails when aider isn't installed yet) and makes the wrapper's
        // intent clear: a missing aider is a hard error, not a silent
        // no-op.
        let real_aider = match which_aider() {
            Some(p) => p,
            None => {
                eprintln!(
                    "error: could not find an 'aider' executable on PATH. \
                     Install aider first (https://aider.chat) and re-run."
                );
                return 1;
            }
        };

        // Refuse to overwrite a symlink: an attacker who can place a
        // symlink at the wrapper path could otherwise cause us to write
        // to the symlink target.
        if let Ok(meta) = fs::symlink_metadata(&path) {
            if meta.file_type().is_symlink() {
                eprintln!(
                    "error: refusing to overwrite symlink at {}. \
                     Remove it manually if you want to install the wrapper.",
                    path.display()
                );
                return 1;
            }
        }

        // For --global installs, also check that the directory is on PATH
        // — otherwise the wrapper would never be invoked.
        if global {
            if let Some(home) = mux_core::platform::home_dir() {
                let bin_dir = home.join(".local").join("bin");
                if let Ok(path_var) = std::env::var("PATH") {
                    if !path_var.split(':').any(|p| std::path::Path::new(p) == bin_dir) {
                        eprintln!(
                            "warning: {} is not on $PATH — the wrapper will be \
                             installed but won't be invoked unless you add it.",
                            bin_dir.display()
                        );
                    }
                }
            }
        }

        let script = wrapper_script(&real_aider);

        if let Err(e) = fs::write(&path, script) {
            eprintln!("error writing {}: {e}", path.display());
            return 1;
        }

        #[cfg(unix)]
        {
            if let Ok(metadata) = fs::metadata(&path) {
                let mut perms = metadata.permissions();
                perms.set_mode(0o755);
                let _ = fs::set_permissions(&path, perms);
            }
        }

        println!("Successfully installed aider wrapper at {}", path.display());
        if !global {
            println!(
                "Note: Remember to run your agent using .bin/aider or prepend .bin to your PATH."
            );
        }
        0
    }
}

/// Generate the bash wrapper script. Issue #97: the report-agent
/// lines invoke the *running* binary by its current_exe() absolute path
/// (shell-quoted — the path can contain spaces), never a bare `mtyx`
/// that a rename or a stale $PATH entry could hijack. Split out of
/// `run_install` so the emitted script is unit-testable without a fake
/// `aider` on $PATH.
fn wrapper_script(real_aider: &str) -> String {
    let bin = hook_merge::shell_quote(&hook_merge::hook_bin());
    format!(
        r#"#!/usr/bin/env bash
# mtyx aider wrapper — generated by mtyx; do not edit by hand.

# Path to the real aider, resolved at install time.
REAL_AIDER="{real_aider}"

if [ -n "${{MTYX_MUX_SURFACE:-}}" ]; then
  {bin} report-agent --surface "$MTYX_MUX_SURFACE" --state working --source aider
fi

# Run the real aider with all arguments
"$REAL_AIDER" "$@"
RESULT=$?

if [ -n "${{MTYX_MUX_SURFACE:-}}" ]; then
  {bin} report-agent --surface "$MTYX_MUX_SURFACE" --state done --source aider
fi

exit $RESULT
"#,
        real_aider = real_aider,
        bin = bin
    )
}

/// Resolve the real `aider` executable on $PATH. We deliberately skip
/// the wrapper's own location to avoid the wrapper recursing into
/// itself. Returns the absolute path to the first match.
fn which_aider() -> Option<String> {
    let path_var = std::env::var("PATH").ok()?;
    for dir in path_var.split(':') {
        if dir.is_empty() {
            continue;
        }
        let candidate = std::path::Path::new(dir).join("aider");
        if let Ok(meta) = fs::symlink_metadata(&candidate) {
            if meta.file_type().is_file() {
                if let Some(p) = candidate.to_str() {
                    return Some(p.to_string());
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Issue #97 AC1: the emitted wrapper invokes the running binary via
    /// its current_exe() absolute path (shell-quoted, so a path with
    /// spaces stays one word), never a bare `mtyx` PATH lookup.
    #[test]
    fn wrapper_script_invokes_the_running_binary_absolute_path() {
        let exe = std::env::current_exe().map(|p| p.display().to_string()).unwrap();
        let script = wrapper_script("/usr/local/bin/aider");
        assert!(
            script.contains(&format!("  {} report-agent", hook_merge::shell_quote(&exe))),
            "both report lines must name the running binary:\n{script}"
        );
        assert_eq!(
            script.matches(&hook_merge::shell_quote(&exe)).count(),
            2,
            "exactly the two report lines invoke mtyx:\n{script}"
        );
        assert!(
            !script.contains("mtyx report-agent"),
            "a bare-mtyx PATH lookup must not survive:\n{script}"
        );
        assert!(
            script.contains("REAL_AIDER=\"/usr/local/bin/aider\""),
            "the real aider path is still embedded:\n{script}"
        );
    }
}
